### ISSUE TITLE
return 403 ,run failed

### ISSUE THREAD

**Issue by gulihua10010** [acheong08/ChatGPT-Proxy-V4#1]
2023/03/15 16:13:01 23368 :8080
Got response: 403 Forbidden
Error: 403 Forbidden
error code: 1020
Error: Failed to refresh puid cookie
2023/03/15 16:13:13 23368 Received SIGINT.
2023/03/15 16:13:13 23368 Waiting for connections to finish...
2023/03/15 16:13:13 23368 Serve() returning...

**Comment by acheong08** [comment]
Did you put access token?

**Comment by acheong08** [comment]
Oh bugfixed
