### ISSUE TITLE
Error: ACCESS_TOKEN and PUID are not set

### ISSUE THREAD

**Issue by frorayz** [acheong08/ChatGPT-Proxy-V4#10]
I already set it via modifying main.go but it still saying when trying to run

**Comment by zyh1222** [comment]
Same issue. Did you find the solution?

**Comment by acheong08** [comment]
Use environment variables.

**Comment by acheong08** [comment]
Remember to `export ACCESS_TOKEN="..." && export PUID="..."`

**Comment by frorayz** [comment]
> Use environment variables.

So I should create an .env with ACCESS_TOKEN and PUID? Or use export? @acheong08

**Comment by acheong08** [comment]
export can be put in `.env` and then `source .env`. It doesn't really matter. Just need environment variables set

**Comment by frorayz** [comment]
> export can be put in `.env` and then `source .env`. It doesn't really matter. Just need environment variables set

Still not working :/

**Comment by acheong08** [comment]
> Got response: 401 Unauthorized
Error: 401 Unauthorized
{"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid_jwt"}}
Error: Failed to refresh puid cookie

It seems your access token is invalid. Try copy and pasting the full thing properly (It has some breaks so it might not have been copied correctly)

**Comment by frorayz** [comment]
> > Got response: 401 Unauthorized
> > Error: 401 Unauthorized
> > {"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid_jwt"}}
> > Error: Failed to refresh puid cookie
> 
> It seems your access token is invalid. Try copy and pasting the full thing properly (It has some breaks so it might not have been copied correctly)

Its a really big thing, so I am not sure how else to paste it properly. It would be really nice if you could just set it on a .env and it would work. I tried sourcing my .env but its not working.

**Comment by acheong08** [comment]
You're meant to put it in .env. It just seems that you didn't copy it correctly to the .env either

**Comment by frorayz** [comment]
> You're meant to put it in .env. It just seems that you didn't copy it correctly to the .env either

<img width="1792" alt="Env" src="https://user-images.githubusercontent.com/32178410/226772612-e65473bf-8378-4970-a7b1-402f218d37b5.png">

This is the wrong way?

**Comment by acheong08** [comment]
Remember to put export in the .env file

**Comment by acheong08** [comment]
And check access token validity via https://jwt.io/

**Comment by frorayz** [comment]
> Remember to put export in the .env file

So it would be export access_token && export puid?
and thanks I will check that

**Comment by acheong08** [comment]
```
export ACCESS_TOKEN="..."
export PUID="..."
```
```
source .env
```

**Comment by frorayz** [comment]
> ```
> export ACCESS_TOKEN="..."
> export PUID="..."
> ```
> 
> ```
> source .env
> ```

Thanks for the instructions but I get a new error, referenced in my above picture.

**Comment by frorayz** [comment]
@acheong08 Any further help on this? ;-;

**Comment by acheong08** [comment]
Internal Server Error means OpenAI is having issues

**Comment by frorayz** [comment]
> Internal Server Error means OpenAI is having issues

Ok lemme try again now

**Comment by frorayz** [comment]
@acheong08 Getting 403 forbidden error, failed to refresh PUID

**Comment by frorayz** [comment]
@acheong08 Getting 403 forbidden error, failed to refresh PUID

**Comment by jhonroxton** [comment]
what is puid

**Comment by jhonroxton** [comment]
> 

what is puid

**Comment by frorayz** [comment]
@acheong08 Any update on this issue?

**Comment by acheong08** [comment]
> > export can be put in `.env` and then `source .env`. It doesn't really matter. Just need environment variables set
> 
> It worked but I get this
> 
> ```
>  - using env:	export GIN_MODE=release
>  - using code:	gin.SetMode(gin.ReleaseMode)
> 
> [GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
> [GIN-debug] GET    /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] POST   /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] PUT    /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] PATCH  /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] HEAD   /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] OPTIONS /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] DELETE /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] CONNECT /api/*path                --> main.proxy (3 handlers)
> [GIN-debug] TRACE  /api/*path                --> main.proxy (3 handlers)
> 2023/03/20 01:40:20 793256 :8080
> Got response: 401 Unauthorized
> Error: 401 Unauthorized
> {"detail":{"message":"Could not parse your authentication token. Please try signing in again.","type":"invalid_request_error","param":null,"code":"invalid_jwt"}}
> Error: Failed to refresh puid cookie
> ```

It means the access token you sent is invalid

**Comment by acheong08** [comment]
and if it continues to return internal server error, it might mean something is wrong with your PUID or access token

**Comment by frorayz** [comment]
> and if it continues to return internal server error, it might mean something is wrong with your PUID or access token

Very weird since my puid and access token works for other bots I host. Not sure what’s wrong here.

**Comment by 1589138103** [comment]
> and if it continues to return internal server error, it might mean something is wrong with your PUID or access token

怎么获得PUID
