### ISSUE TITLE
how can I use python 

### ISSUE THREAD

**Issue by xxllp** [acheong08/ChatGPT-Proxy-V4#12]
Is there an python code ？

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT

**Comment by xxllp** [comment]
I have use this code  use revChatGPT.V1 but fail now ，get the error 
`tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/api/auth/session": dial tcp 157.240.12.50:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

**Comment by acheong08** [comment]
Internet errors are out of scope. OpenAI blocked in China

**Comment by xxllp** [comment]
是不是要用代理啥的才可以解决这个问题
