### ISSUE TITLE
Error: Failed to refresh puid cookie

### ISSUE THREAD

**Issue by s00466019** [acheong08/ChatGPT-Proxy-V4#15]
![image](https://user-images.githubusercontent.com/99530842/226849660-c64d6133-0f41-4a6d-9bc1-71f0557e4559.png)

**Comment by s00466019** [comment]
> I have tried to set both ACCESS_TOKEN and PUID in the environment variables and the code works well without this error. The PUID must be new. I hope it may help you.

It works,thx a lot!

**Comment by FerryboatSeranade** [comment]
I also encounter the same problem, I am sure of ACCESS_TOKEN and PUID is the latest.

**Comment by linyunyx** [comment]
> I have tried to set both ACCESS_TOKEN and PUID in the environment variables and the code works well without this error. The PUID must be new. I hope it may help you.

Could you please tell me where I can obtain my PUID? Thank you.

**Comment by s00466019** [comment]
> > I have tried to set both ACCESS_TOKEN and PUID in the environment variables and the code works well without this error. The PUID must be new. I hope it may help you.
> 
> Could you please tell me where I can obtain my PUID? Thank you.

in cookie

**Comment by jhonroxton** [comment]
> > > I have tried to set both ACCESS_TOKEN and PUID in the environment variables and the code works well without this error. The PUID must be new. I hope it may help you.
> > 
> > 
> > Could you please tell me where I can obtain my PUID? Thank you.
> 
> in cookie
only chatgpt4 can get PUID by cookie, i'm not sure, i can not find it in my chatgpt3.5 cookies!
