### ISSUE TITLE
return 500 by openai

### ISSUE THREAD

**Issue by aLittleFat** [acheong08/ChatGPT-Proxy-V4#19]
openai return 500 Internal Server Error

**Comment by lp1014978271** [comment]
yes



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 03/27/2023 18:03 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [acheong08/ChatGPT-Proxy-V4] return 500 by openai (Issue #19) |

me too
