### ISSUE TITLE
What exactly is puid and access_token? 

### ISSUE THREAD

**Issue by frorayz** [acheong08/ChatGPT-Proxy-V4#2]
Where do you find them? is access_token __Secure-next-auth.session-token? and what is the puid taken from?

**Comment by acheong08** [comment]
access_token is what you get from https://chat.openai.com/api/auth/session

`_puid` is found in cookies of paid users

**Comment by acheong08** [comment]
You only need access_token unless your IP is banned by OpenAI

**Comment by frorayz** [comment]
> access_token is what you get from https://chat.openai.com/api/auth/session
> 
> `_puid` is found in cookies of paid users

@acheong08 so where is it I don't see it in my cookies? 

<img width="608" alt="Hm" src="https://user-images.githubusercontent.com/32178410/225254764-5c985402-852f-450f-a5f7-d703660413e4.png">

**Comment by acheong08** [comment]
Requires plus account

**Comment by frorayz** [comment]
> Requires plus account

I have plus account?

**Comment by acheong08** [comment]
Then refresh your page. It should be there

**Comment by frorayz** [comment]
> Then refresh your page. It should be there

Ah never mind found it, thanks!!
