### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by h3z** [acheong08/ChatGPT-Proxy-V4#23]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/28476985/228612536-c2298ab0-d994-4810-a738-d83e1917eb87.png">

I have set ACCESS_TOKEN and PUID. 
And satisfy the requirements
* `ChatGPT plus account`
* `Access to chat.openai.com`

Then got the error 404.   How to fix that?

**Comment by h3z** [comment]
use ChatGPT-web as client

**Comment by Jirafey** [comment]
> ChatGPT-web

wdym ?

**Comment by h3z** [comment]
> > ChatGPT-web
> 
> wdym ?

this proxy url is: `http://ip:port/api/conversation`  not `http://ip:port`  😂

**Comment by Jirafey** [comment]
> > > ChatGPT-web
> > 
> > 
> > wdym ?
> 
> this proxy url is: `http://ip:port/api/conversation` not `http://ip:port` 😂

omg fr
