### ISSUE TITLE
405 when accessing /api/conversation

### ISSUE THREAD

**Issue by Jirafey** [acheong08/ChatGPT-Proxy-V4#25]
Proxy:
[GIN] 2023/03/31 - 09:59:47 | 404 |  179.137025ms |        10.0.2.2 | GET      "/api/"
[GIN] 2023/03/31 - 09:59:50 | 405 |  178.347612ms |        10.0.2.2 | GET      "/api/conversation"
[GIN] 2023/03/31 - 10:01:21 | 200 |     259.397µs |        10.0.2.2 | GET      "/ping"

Host:
{"detail":"Not Found"} (404)
{"detail":"Method Not Allowed"} (405)
{"message":"pong"} (200)

**Comment by acheong08** [comment]
You're using it wrong.

**Comment by acheong08** [comment]
Check revChatGPT source code

**Comment by Jirafey** [comment]
yeah i kind of figured it afterwards, forgot to close it
