### ISSUE TITLE
GPT not plus ,can use this tool?

### ISSUE THREAD

**Issue by justincnn** [acheong08/ChatGPT-Proxy-V4#26]

**Comment by acheong08** [comment]
use public proxy. `https://bypass.churchless.tech/`

**Comment by RynKings** [comment]
I am sorry How ?

> use public proxy. `https://bypass.churchless.tech/`

**Comment by RynKings** [comment]
> use public proxy. `https://bypass.churchless.tech/`

I am sorrry how ?

**Comment by justincnn** [comment]
> use public proxy. `https://bypass.churchless.tech/`

it does not  work for me:(

**Comment by dingiso** [comment]
Have a look at this part https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
