### ISSUE TITLE
Question: can I use it with revChatGPT

### ISSUE THREAD

**Issue by fecet** [acheong08/ChatGPT-Proxy-V4#29]
How can I use it with https://github.com/acheong08/ChatGPT, or I have to implement that by myself?

**Comment by acheong08** [comment]
That is what it's meant for:
```
CHATGPT_BASE_URL="http://localhost:8080/api/" python3 -m revChatGPT.V1
```

**Comment by acheong08** [comment]
replace the URL as you wish

**Comment by acheong08** [comment]
It's an environment variable

**Comment by fecet** [comment]
Got it!
