### ISSUE TITLE
用docker部署好之后如何使用

### ISSUE THREAD

**Issue by pengfeiu** [acheong08/ChatGPT-Proxy-V4#30]
生成的反向代理地址路径是什么，直接访问页面显示404

**Comment by pengfeiu** [comment]
ip/api/conversation

> 生成的反向代理地址路径是什么，直接访问页面显示404

**Comment by EvanDbg** [comment]
API_REVERSE_PROXY=http://chatgpt-proxy-server-ip:8080/api/conversation
