### ISSUE TITLE
ChatGPT error 429

### ISSUE THREAD

**Issue by zazayaya** [acheong08/ChatGPT-Proxy-V4#32]
[ChatGPT error 429: {"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}]

**Comment by EvanDbg** [comment]
一次只有一条消息。在发送另一条消息之前，请等待任何其他响应完成，或者等待一分钟。

**Comment by zazayaya** [comment]
嗯，已经限制并发了
