### ISSUE TITLE
Where do puid come from?

### ISSUE THREAD

**Issue by nildebug** [acheong08/ChatGPT-Proxy-V4#33]
Where do puid come from?  I don't have a puid field in my cookie

**Comment by EvanDbg** [comment]
Purchase ChatGPT Plus first, then you can get puid in your cookie.

**Comment by ludashi2020** [comment]
> Purchase ChatGPT Plus first, then you can get puid in your cookie.

ACCESS_TOKEN  come from cookie too?

**Comment by acheong08** [comment]
https://chat.openai.com/api/auth/session

**Comment by ludashi2020** [comment]
> https://chat.openai.com/api/auth/session

Thank you very much
