### ISSUE TITLE
Failed to refresh puid token while puid token and ACCESS_TOKEN are all set

### ISSUE THREAD

**Issue by wangjiyang** [acheong08/ChatGPT-Proxy-V4#34]
$ ChatGPT-Proxy-V4
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] GET    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PUT    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PATCH  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] HEAD   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] OPTIONS /api/*path                --> main.proxy (3 handlers)
[GIN-debug] DELETE /api/*path                --> main.proxy (3 handlers)
[GIN-debug] CONNECT /api/*path                --> main.proxy (3 handlers)
[GIN-debug] TRACE  /api/*path                --> main.proxy (3 handlers)
2023/04/03 20:40:22 2243901 :8080
Error: Failed to refresh puid cookie

**Comment by 1176643033** [comment]
I have also encountered the same issue. Has it been resolved now?
