### ISSUE TITLE
What is the LICENSE?

### ISSUE THREAD

**Issue by wesen** [acheong08/ChatGPT-Proxy-V4#35]
I have adapted this proxy for my own use, and I was wondering what the license is and if I can publish my tweaks

**Comment by acheong08** [comment]
Added. https://github.com/acheong08/ChatGPT-Proxy-V4/blob/main/LICENSE

```
The Unlicense
A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.
```

**Comment by acheong08** [comment]
You can do anything you want with it
