### ISSUE TITLE
I'm a novice，after go install github.com/acheong08/ChatGPT-Proxy-V4@latest，how to start

### ISSUE THREAD

**Issue by jtwgo** [acheong08/ChatGPT-Proxy-V4#37]
after execute go install github.com/acheong08/ChatGPT-Proxy-V4@latest，how can i use?I'm a novice
![image](https://user-images.githubusercontent.com/24961858/229741939-4c16b9da-e34c-41a2-9ba0-f433504ac357.png)

**Comment by gvamvou** [comment]
Hello! I had the same problem. After some digging I found the soultion:
1. find the path of go bin `go env GOPATH`
2. cd to that path, there should be a bin folder
3. inside the bin folder, you can run the executable by `./ChatGPT-Proxy-V4`
