### ISSUE TITLE
403错误

### ISSUE THREAD

**Issue by xiaoguaishou92** [acheong08/ChatGPT-Proxy-V4#39]
部署完成后报403，是不是因为部署这个代理服务的机器被墙了。大家有啥可以用的云机推荐么

**Comment by flyingzhang** [comment]
seems now requests with puid cookies  needs cf_clearance cookie  too.  need some solutions to get/refresh cf_clearance.

**Comment by acheong08** [comment]
It doesn't. You just need to ensure you put PUID and PUID is valid

**Comment by acheong08** [comment]
Remember to update PUID every few days

**Comment by flyingzhang** [comment]
so.. even when I have set the correct ACCESS_TOKEN, the puid still cannot update automatically?

**Comment by flyingzhang** [comment]
> Remember to update PUID every few days
I updated the PUID  fetched from browser, but  on my aws ECS instance in US I still got 403 with CF 1020 error.  I have tried to emulate a request with curl  including a valid cf_clearance cookie, that successed.

**Comment by acheong08** [comment]
Assuming access token not set. If access token set, remember to refresh every 2 weeks

**Comment by acheong08** [comment]
If you only put access token and not PUID, it will throw error if IP blocked
