### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Omar-Alodwan** [acheong08/ChatGPT-Proxy-V4#42]
```

> go install github.com/acheong08/ChatGPT-Proxy-V4@latest


# github.com/fvbock/endless
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:64:11: undefined: syscall.SIGUSR1
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:65:11: undefined: syscall.SIGUSR2
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:68:11: undefined: syscall.SIGTSTP
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:111:13: undefined: syscall.SIGUSR1
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:112:13: undefined: syscall.SIGUSR2
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:115:13: undefined: syscall.SIGTSTP
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:119:13: undefined: syscall.SIGUSR1
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:120:13: undefined: syscall.SIGUSR2
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:123:13: undefined: syscall.SIGTSTP
..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: undefined: syscall.Kill..\..\go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: too many errors
```

**Comment by INSIinc** [comment]
**same as you**# github.com/fvbock/endless
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:64:11: undefined: syscall.SIGUSR1
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:65:11: undefined: syscall.SIGUSR2
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:68:11: undefined: syscall.SIGTSTP
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:111:13: undefined: syscall.SIGUSR1
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:112:13: undefined: syscall.SIGUSR2
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:115:13: undefined: syscall.SIGTSTP
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:119:13: undefined: syscall.SIGUSR1
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:120:13: undefined: syscall.SIGUSR2
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:123:13: undefined: syscall.SIGTSTP
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: undefined: syscall.Kill
go\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: too many errors
