### ISSUE TITLE
How to get the ACCESS_TOKEN ?

### ISSUE THREAD

**Issue by bing-h** [acheong08/ChatGPT-Proxy-V4#45]
Is it a alias of Secret key? if true , what function the program do？

**Comment by Tostino** [comment]
Go here: https://chat.openai.com/api/auth/session and look for the "access_token" part of the json after you have logged in to the website on your browser.

**Comment by acheong08** [comment]
> What the program do, allow multi-user use webpage chatgpt in one account?

Multiple users share 1 PUID to get around cloudflare

**Comment by bing-h** [comment]
It sounds good,  will it still work if the request ip is banned by cloudflare verification?

**Comment by acheong08** [comment]
if you have PUID, yes
