### ISSUE TITLE
服务器不支持ChatGPT，可以使用socks或http代理么？

### ISSUE THREAD

**Issue by faidev** [acheong08/ChatGPT-Proxy-V4#46]
服务器不支持ChatGPT，可以使用socks或http代理么？

**Comment by faidev** [comment]
![image](https://user-images.githubusercontent.com/20348767/230874054-0c47b48d-3ea2-44be-82a8-3cdb8661c16d.png)
已经解决了！可以正常用了

**Comment by byxinyu** [comment]
请问是怎设置socks的？
