### ISSUE TITLE
Error 404 despite having set CHATGPT_BASE_URL

### ISSUE THREAD

**Issue by Arche151** [acheong08/ChatGPT-Proxy-V4#48]
So, I exported the PUID and Access token via `export ACCESS_TOKEN="..." & export PUID="..."` in the repos' directory on my Linux machine.

When starting the server, I get the ol' 404: Not found error.

@acheong08 suggested [here](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/22) that a CHATGPT_BASE_URL environment variable has to be set. 

But no matter what I set as the value, I keep getting 404. I entered `export CHATGPT_BASE_URL="https://chat.openai.com/chat?model=gpt-4"` in the bin directory just like I did with the PUID and Access Token, but I got the same error. Changing the Base URL to chat.openai.com or different variations didn't help.

Can someone - maybe hopefully @acheong08 themselves - help?

**Comment by acheong08** [comment]
`CHATGPT_BASE_URL` is for the revChatGPT library. You set it to your proxy instance.

**Comment by acheong08** [comment]
> When starting the server, I get the ol' 404: Not found error.

Where are you getting this?

**Comment by Arche151** [comment]
> > When starting the server, I get the ol' 404: Not found error.
> 
> Where are you getting this?

Hey, thanks for the quicky reply! I am getting the error in the terminal of my Linux machine while trying to launch the Proxy.

`administrator@administrator:~/go/bin$ ./ChatGPT-Proxy-V4
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] GET    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] POST   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PUT    /api/*path                --> main.proxy (3 handlers)
[GIN-debug] PATCH  /api/*path                --> main.proxy (3 handlers)
[GIN-debug] HEAD   /api/*path                --> main.proxy (3 handlers)
[GIN-debug] OPTIONS /api/*path                --> main.proxy (3 handlers)
[GIN-debug] DELETE /api/*path                --> main.proxy (3 handlers)
[GIN-debug] CONNECT /api/*path                --> main.proxy (3 handlers)
[GIN-debug] TRACE  /api/*path                --> main.proxy (3 handlers)
2023/04/10 04:13:37 214481 :8080
Got response: 200 OK
puid: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[GIN] 2023/04/10 - 04:15:18 | 404 |         536ns |       127.0.0.1 | GET      "/"
[GIN] 2023/04/10 - 04:15:24 | 404 |       1.628µs |       127.0.0.1 | GET      "/"
[GIN] 2023/04/10 - 04:15:24 | 404 |       1.583µs |       127.0.0.1 | GET      "/"
[GIN] 2023/04/10 - 04:15:24 | 404 |       1.323µs |       127.0.0.1 | GET      "/"

`

**Comment by Arche151** [comment]
> 

I'm sorry, I don't really understand what you mean by that. :( Basically, I want to use the GPT-4 API (I only have access to it via ChatGPT Plus) and it seemed to me like your repo would help achieve that.

**Comment by Arche151** [comment]
> `CHATGPT_BASE_URL` is for the revChatGPT library. You set it to your proxy instance.

I'm sorry, I don't really understand what you mean by that. :( Basically, I want to use the GPT-4 API (I only have access to it via ChatGPT Plus) and it seemed to me like your repo would help achieve that.
