### ISSUE TITLE
About the integration of this tool with `ChatGPT` from scratch.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT-Proxy-V4#5]
If I compile this tool from scratch and run it correctly, does it mean that the relevant API token in [ChatGPT](https://github.com/acheong08/ChatGPT) does not need to be configured separately?

**Comment by acheong08** [comment]
Yes. The only difference would be the `CHATGPT_BASE_URL` environment variable you need to set
