### ISSUE TITLE
按照步骤安装启动 报 500 [OpenAI] 服务器繁忙，请稍后再试 | Internal Server Error

### ISSUE THREAD

**Issue by lizhongyuan3** [acheong08/ChatGPT-Proxy-V4#53]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/44236581/232218173-f0087724-5785-4473-9f72-d7180d093e0d.png">
chat-web .env 配置的 API_REVERSE_PROXY 为 http://localhost:8080/api/conversation

**Comment by Cicinnus0407** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/15153456/232232304-12b4339f-3f24-4175-9bcf-36ad288703cf.png">
the same question,
