### ISSUE TITLE
bypass.churchless.tech: 502 Bad Gateway

### ISSUE THREAD

**Issue by sam-hieken** [acheong08/ChatGPT-Proxy-V4#57]
Hello,

Ran into some trouble using [the unofficial ChatGPT API](https://github.com/transitive-bullshit/chatgpt-api) today; looks like it's caused by a Bad Gateway from bypass.churchless.tech (my apologies if this isn't the correct repository for churchless). 

[Here's an example response](https://imgur.com/a/r6Y7y0W) after trying to query all conversations. I didn't show my access token for obvious reasons, but it's valid & non expired (plus, the endpoint seems to fail regardless of a valid token). 

Thanks.

**Comment by BlusteryS** [comment]
same
