### ISSUE TITLE
Proxy-V4 seems working well but revChatGPT/V1.py got 403

### ISSUE THREAD

**Issue by chushj** [acheong08/ChatGPT-Proxy-V4#58]
Proxy-V4 shows
[GIN] 2023/04/17 - 03:52:06 | 403 |    55.76265ms |       127.0.0.1 | GET      "/api/conversation/cc726f70-4963-1cf5-b0bd-faf50560d26a"
[GIN] 2023/04/17 - 03:52:06 | 403 |    8.479793ms |       127.0.0.1 | POST     "/api/conversation"

revChatGPT/V1.py shows
  File "/home/ec2-user/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 696, in __check_response
    raise error from e
revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)

But revChatGPT/V1.py works well with the default proxy https://chat.gateway.do/api/

**Comment by dawhdb** [comment]
我Proxy-V4的是403，环境变量里加了puid这些，请问是还有哪里需要弄吗
![1](https://user-images.githubusercontent.com/125231265/232417580-d8aae753-c1c3-4f2b-be8b-d75fc52ab0b8.png)

**Comment by chushj** [comment]
Oh, I got 403 too. I noticed that there are two cf_clearance cookies in the request, and I noticed that timeouts in the browser happen frequently.(So the page was initialized to new chat)"

**Comment by Walbre** [comment]
I've got the same problem, any way to fix it ?

**Comment by chushj** [comment]
From https://github.com/acheong08/ChatGPT

> Due to recent tightening of OpenAI's security, the default endpoint has been swapped over to one provided by @pengzhile. It is not open source and privacy is not guarenteed. Use it at your own risk. I am working on an open source implementation with the latest changes but that could take a while.
