### ISSUE TITLE
what's the difference between ChatGPT-Proxy-V1 and ChatGPT-Proxy-V4?

### ISSUE THREAD

**Issue by jackywu** [acheong08/ChatGPT-Proxy-V4#6]
thanks for your works, can you tell some details difference between them？I have to make a choice between them.

**Comment by acheong08** [comment]
V1 no longer works

**Comment by jackywu** [comment]
is this reverse proxy  `https://bypass.duti.tech/api/conversation` still works ?  where is the code repo ? can I setup a private proxy for myself ?

**Comment by acheong08** [comment]
yes. the code for thus repo is in this repo...

**Comment by jackywu** [comment]
does this proxy `https://bypass.duti.tech/api/conversation`  has rate limitation？ if has , what it is ?  thanks .
