### ISSUE TITLE
Documentation!!!

### ISSUE THREAD

**Issue by p4w4n** [acheong08/ChatGPT-Proxy-V4#63]
Hey!!!
Thanks for this awesome project. Can you please provide some more documentation and its features?
Is this project only a proxy server? Or can it also get the access tokens using the email:password? I think not, but can I use your chatgpt-to-api project to achieve that functionality combined with this project?

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-to-API can work alone without a proxy (given clean IP)

**Comment by acheong08** [comment]
>  Or can it also get the access tokens using the email:password?

https://github.com/acheong08/OpenAIAuth

There is a repo for everything

**Comment by p4w4n** [comment]
chatgpttoapi  | Location: begin
chatgpttoapi  | Status code: 0
chatgpttoapi  | Details:
chatgpttoapi  | Embedded error: Get **"https://chat.openai.com/api/auth/csrf": x509: certificate signed by unknown authority**

getting this while running from docker. tried installing certificates through dockerfile but didn't work.



RUN apk update && \
    apk add --no-cache openssl ca-certificates && \
    wget -O /usr/local/share/ca-certificates/RootCA.crt https://letsencrypt.org/certs/isrgrootx1.pem.txt && \
    echo -n | openssl s_client -servername chat.openai.com -connect chat.openai.com:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/share/ca-certificates/OpenAI.crt && \
    update-ca-certificates

**Comment by acheong08** [comment]
idk how to fix in docker. Just run it outside of container
