### ISSUE TITLE
support login

### ISSUE THREAD

**Issue by zwluoqi** [acheong08/ChatGPT-Proxy-V4#71]
i find the project https://github.com/linweiyuan/go-chatgpt-api can support login api。
![image](https://github.com/acheong08/ChatGPT-Proxy-V4/assets/3363485/ddbf6881-6854-4dca-b2ab-9658fa3f14bd)
this project had support?

**Comment by acheong08** [comment]
Hi. I won't support it here because of rate limits (~20 accounts per 10 minutes)
You can find my reverse engineering of auth here: https://github.com/acheong08/OpenAIAuth (No cloudflare no matter the IP)
