### ISSUE TITLE
Mac Build Error

### ISSUE THREAD

**Issue by zwluoqi** [acheong08/ChatGPT-Proxy-V4#72]
in win11 is working,
but in my mac
OS:12.6.2 Monterey
GO:go1.20.4 darwin/amd64

```
go build .
package github.com/acheong08/ChatGPT-Proxy-V4
	imports github.com/acheong08/endless
	imports github.com/acheong08/endless/signals: build constraints exclude all Go files in /Users/zhouwei/go/pkg/mod/github.com/acheong08/endless@v0.0.0-20230522010333-1359fd84c836/signals

```

i find the version is the leteast
<img width="1375" alt="image" src="https://github.com/acheong08/ChatGPT-Proxy-V4/assets/3363485/92076d13-bce6-4344-be6b-962d251ef7b1">

**Comment by zwluoqi** [comment]
use leatest released code can working。
https://github.com/acheong08/ChatGPT-Proxy-V4/releases

**Comment by t1maccapp** [comment]
What helped me is specifying build tag, in rep folder:
```
go build --tags=macos .
```

**Comment by acheong08** [comment]
Fixed in https://github.com/acheong08/ChatGPT-Proxy-V4/commit/e6c9cba6d261fd9aa2525595e93c33cfdda6ff97
