### ISSUE TITLE
revChatGPT.typings.Error (code 403) using V1 for non GPT-3.5 models

### ISSUE THREAD

**Issue by Ai-Austin** [acheong08/ChatGPT-Proxy-V4#77]
I'm not sure if this is something I am not doing correct with revChatGPT or if it is related to the proxy. When I dont specify a model, the API's ask function works flawless. When I specify any gpt-4 model on my account with chatgpt plus, I get this error message:
`revChatGPT.typings.Error: OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)`

I wonder if setting up my own proxy would solve it?

**Comment by acheong08** [comment]
It might be detecting a conflict in PUID. I'll add some mitigation tomorrow.

> I wonder if setting up my own proxy would solve it?

Yes if you use the same plus account

**Comment by Ai-Austin** [comment]
I assume that PUID update worked and everyone is jamming your server now? 
revChatGPT is giving a giant html response from cloudflare in terminal.
`The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524">Additional troubleshooting information here.`
I'm going to try a local server to see if that solves and will update. Anyways, thanks for all you are doing for open source!  @archeong08
