### ISSUE TITLE
Our systems have detected unusual activity from your system. Please try again later."} (code: 403)

### ISSUE THREAD

**Issue by maxduke** [acheong08/ChatGPT-Proxy-V4#78]
Recently I encountered this error when using GPT-4 model. (GPT-4 mobile works fine).
Instead of specifying PUID in environment variable, I only specified OPENAI_EMAIL and OPENAI_PASSWORD for auto refresh of PUID.

**Comment by acheong08** [comment]
Any thoughts on what they could be using to detect this?

**Comment by JoshMayberry** [comment]
I'm not sure what I did, but I'm getting this error too.

**Comment by qingxiangguo** [comment]
Just got this one minute ago. Decide to wait.

**Comment by bokkenote** [comment]
got the same error too.

**Comment by AlexShrestha** [comment]
same

**Comment by davidor23** [comment]
Try using firefox if you'vebeen using Google Chrome. It worked for me on GPT-4.

**Comment by samgable27** [comment]
tried it on Firefox and Chrome, both getting the same error.

**Comment by sadata7** [comment]
Same here.

**Comment by jreniel** [comment]
Same!!

**Comment by Famaqo2000** [comment]
same haha

**Comment by Quantum155** [comment]
FYI: I'm getting the same error message right now using ChatGPT normally. Might be a more widespread technical error.

**Comment by FrostByteFreddy** [comment]
Same here. I was using it to write a script for setting up projects. Guess they think we're trying to hack or smth lmao

**Comment by sadata7** [comment]
If you just keep editing the prompt and then hitting Save & Submit, it will eventually work.  A few times I had to repeat 10 to 20 times.

**Comment by jreniel** [comment]
I logged in from Edge and it worked (coming from firefox)

**Comment by oxue** [comment]
What were you guys using chatgpt for when it errored? I wonder if the subject matter of your usage has anything to do with this phenomenon.

**Comment by davidor23** [comment]
> I logged in from Edge and it worked (coming from firefox)

I think changing browsers might be temporary fix as going from Chrome to Firefox fixed it for me.

**Comment by jreniel** [comment]
> What were you guys using chatgpt for when it errored? I wonder if the subject matter of your usage has anything to do with this phenomenon.

Wouldn't doubt it for a second

**Comment by davidolsonj** [comment]
I was using the Show Me plugin and getting the same error

**Comment by tunahorse** [comment]
Just a heads up everybody, seems like this might be a widespread issue not directly related.

**Comment by hackedpassword** [comment]
Same.

**Comment by KJSavinelli** [comment]
I was getting the same error, but it seems to be working now for me.

**Comment by WillKre** [comment]
Also getting this just using the usual website

<img width="633" alt="image" src="https://github.com/acheong08/ChatGPT-Proxy-V4/assets/7396157/4b19f68a-5365-4c9b-97a2-9ff02c447149">

**Comment by Quantum155** [comment]
Can confirm, switching from firefox to chrome (chromium) solved the issue. Try switching browsers for now.

**Comment by abgita** [comment]
Removing all data from the page and logging again fixes the issue in Firefox

**Comment by acheong08** [comment]
Could be new `arkose_token` I see in payload

**Comment by acheong08** [comment]
It comes from a POST request to `https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147`

**Comment by acheong08** [comment]
Seems to be part of funcaptcha. They have 1000 JS challenges to pass which generates the payload token

**Comment by acheong08** [comment]
After checking a bit, it seems we don't need to pass the JS challenge at all. The tokens are pretty much the same:
```diff
--- 1.txt	2023-06-14 18:17:43.958660949 +0800
+++ 2.txt	2023-06-14 18:17:49.826588350 +0800
@@ -1,4 +1,4 @@
-59217687ee420a9b5.8640058204
+50617687eb83b4f97.7845647404
 r=ap-southeast-1
 meta=3
 meta_width=300
@@ -8,9 +8,10 @@
 pk=35536E1E-65B4-4D96-9D97-6ADB7EFF8147
 at=40
 sup=1
-rid=60
+rid=2
 ag=101
 cdn_url=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc
 lurl=https%3A%2F%2Faudio-ap-southeast-1.arkoselabs.com
 surl=https%3A%2F%2Ftcr9i.chat.openai.com
 smurl=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager
+
```

**Comment by acheong08** [comment]
The first value appears to be a timestamp but I'm unsure about the rid

**Comment by acheong08** [comment]
Check https://github.com/acheong08/ChatGPT/releases/tag/6.2.2 and see if it works

**Comment by Daedra22** [comment]
> Check https://github.com/acheong08/ChatGPT/releases/tag/6.2.2 and see if it works

Still got the same error :( even with the 6.2.2 version

**Comment by acheong08** [comment]
could you guys check your arkose tokens to see what the difference is?

**Comment by acheong08** [comment]
yes

**Comment by tongxinrang** [comment]
me too

**Comment by acheong08** [comment]
Fixed on latest version of revChatGPT.
