### ISSUE TITLE
how to fix the error "Our systems have detected unusual activity from your system. Please try again later."

### ISSUE THREAD

**Issue by flyingpot** [acheong08/ChatGPT-Proxy-V4#83]
I'm trying to integrate this project with [pandora](https://github.com/pengzhile/pandora). Everything else is working well, but when I'm trying to make gpt-4 (including mobile version) conversation, this error happens: "Our systems have detected unusual activity from your system. Please try again later."
I noticed that you mentioned in this [issue](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/78) you have fixed the problem. Could you provide some information about why this error may happen and how you fix it?

**Comment by WhiteCranes** [comment]
This issue has indeed occurred before, and the author has already fixed it. I just encountered the same problem, indicating that it was caused by a new reason.

**Comment by acheong08** [comment]
fixed

**Comment by Hisir0909** [comment]
> I'm trying to integrate this project with [pandora](https://github.com/pengzhile/pandora). Everything else is working well, but when I'm trying to make gpt-4 (including mobile version) conversation, this error happens: "Our systems have detected unusual activity from your system. Please try again later."我正在尝试将这个项目与潘多拉集成。其他一切正常，但是当我尝试进行 gpt-4（包括移动版本）对话时，会发生此错误：“我们的系统检测到您的系统中存在异常活动。请稍后再试。 I noticed that you mentioned in this [issue](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/78) you have fixed the problem. Could you provide some information about why this error may happen and how you fix it?我注意到您在此问题中提到您已经解决了问题。您能否提供有关为什么会发生此错误以及如何解决它的一些信息？



> I'm trying to integrate this project with [pandora](https://github.com/pengzhile/pandora). Everything else is working well, but when I'm trying to make gpt-4 (including mobile version) conversation, this error happens: "Our systems have detected unusual activity from your system. Please try again later."我正在尝试将这个项目与潘多拉集成。其他一切正常，但是当我尝试进行 gpt-4（包括移动版本）对话时，会发生此错误：“我们的系统检测到您的系统中存在异常活动。请稍后再试。 I noticed that you mentioned in this [issue](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/78) you have fixed the problem. Could you provide some information about why this error may happen and how you fix it?我注意到您在此问题中提到您已经解决了问题。您能否提供有关为什么会发生此错误以及如何解决它的一些信息？

I noticed that you have integrated this project with Pandora. I am curious about how you achieved this integration. I have been attempting to use Pandora Cloud with this project, but I have been unsuccessful.

**Comment by Hisir0909** [comment]
> I'm trying to integrate this project with [pandora](https://github.com/pengzhile/pandora). Everything else is working well, but when I'm trying to make gpt-4 (including mobile version) conversation, this error happens: "Our systems have detected unusual activity from your system. Please try again later." I noticed that you mentioned in this [issue](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/78) you have fixed the problem. Could you provide some information about why this error may happen and how you fix it?

I noticed that you have integrated this project with Pandora. I am curious about how you achieved this integration. I have been attempting to use Pandora Cloud with this project, but I have been unsuccessful.

**Comment by flyingpot** [comment]
I'm now using this proxy (https://github.com/flyingpot/chatgpt-proxy), and
change the environment variables CHATGPT_API_PREFIX from pandora to the
proxy domain.

Hisir ***@***.***> 于2023年6月26日周一 10:25写道：
