### ISSUE TITLE
is this the same thing as  the proxy on "bypass.churchless.tech"

### ISSUE THREAD

**Issue by hydeCaesar** [acheong08/ChatGPT-Proxy-V4#96]
I tried to set up my own proxy to avoid the rate limit using [ChatGPTProxy](https://github.com/acheong08/ChatGPTProxy) - main branch, changing my revChatGPT.V1 config using "chatbot.baseUrl = host:port"
it obviously got an 404, when i tried "chatbot.ask(prompt)" .
when I change it to "chatbot.baseUrl = host:port/api/" it seems that "host:9090/api/conversation" doesn't work while "bypass.churchless.tech/conversation" does. 
is there any chance i can use a local proxy just like I use "bypass.churchless.tech"

**Comment by acheong08** [comment]
It should be identical. bypass.churchless.tech is deployed directly from the release binary here

**Comment by hydeCaesar** [comment]
My fault, I used an unstable server.
